// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/myza/domain"
	mock "github.com/stretchr/testify/mock"
)

// CryptoAddressGenerator is an autogenerated mock type for the CryptoAddressGenerator type
type CryptoAddressGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: context
func (_m *CryptoAddressGenerator) Generate(context domain.AddressGeneratorContext) (domain.Address, error) {
	ret := _m.Called(context)

	var r0 domain.Address
	if rf, ok := ret.Get(0).(func(domain.AddressGeneratorContext) domain.Address); ok {
		r0 = rf(context)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.AddressGeneratorContext) error); ok {
		r1 = rf(context)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
