// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/myza/domain"
	mock "github.com/stretchr/testify/mock"
)

// ExchangeRateConverter is an autogenerated mock type for the ExchangeRateConverter type
type ExchangeRateConverter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: _a0, _a1
func (_m *ExchangeRateConverter) Convert(_a0 *domain.Wallet, _a1 domain.FiatCurrency) (float64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 float64
	if rf, ok := ret.Get(0).(func(*domain.Wallet, domain.FiatCurrency) float64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Wallet, domain.FiatCurrency) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
