// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/myza/domain"
	mock "github.com/stretchr/testify/mock"
)

// TextHandler is an autogenerated mock type for the TextHandler type
type TextHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: request
func (_m *TextHandler) Handle(request domain.TextRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.TextRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
